### ISSUE TITLE
Такого не должно быть в исходниках

### ISSUE THREAD

**Issue by Alex-Kostenko** [maksimanom/testTaskSpd#10]
https://github.com/maksimanom/testTaskSpd/blob/c60df712ead41bb930d6744eedf572260f780823/src/scss/hover.scss#L33

Все эти апрефиксы должны ставиться галпом во время компиляции, 
https://autoprefixer.github.io/ru/

**Comment by maksimanom** [comment]
Понял, смотрел на border, a с помощью outline можно создать рамку во внутрь, убрал.
