### ISSUE TITLE
Font family должен наследоваться от родителя

### ISSUE THREAD

**Issue by Alex-Kostenko** [maksimanom/testTaskSpd#8]
https://github.com/maksimanom/testTaskSpd/blob/c60df712ead41bb930d6744eedf572260f780823/src/scss/main.scss#L465

Допустим дизайнер захотел сменить шрифты и тебе приведется  его менять кучу раз, вместо 1

**Comment by maksimanom** [comment]
там были блоки с обоими шрифтами и в родительский "нельзя" добавить один, ибо у чайлда будет другой его перекрывать. Или лучше пускай перекрывает?

**Comment by maksimanom** [comment]
Или лучше просто @mixin прописать (ну или переменную %).
